### ISSUE TITLE
Is this feasible?

### ISSUE THREAD

**Issue by GeorgeS2019** [will-maclean/sb3-burn#36]
[Porting sb3-burn to c# Torchsharp](https://github.com/dotnet/TorchSharp/discussions/1333)

I am not familiar with burn. However, I am interested how you approach the pytorch version of sb3 while porting that to rust. 

Is this feasible?

Interested of learning the challenges you have while porting sb3 from Pytorch to rust using burn

**Comment by will-maclean** [comment]
Hi, thanks for the question. Yes, the conversion of stable-baselines3 from python/pytorch to rust/burn is going quite well. The core design is more stabilised now and the library is at the point where we can start adding features (such as checkpointing and more advanced logging) and new algorithms.

Personally, I'd say the biggest challenges have been in finding ways of converting the abstract classes / inheritance structure of sb3 into the rust structures of traits and generics. But if you're converting into C# then this shouldn't be much of an issue. The other big factor is availability of a flexible deep learning library. Rust is lucky to have [burn](https://github.com/tracel-ai/burn), which is both flexible and also has a good community of developers, but I don't know what options are available in C#.

Let me know if you have any more questions.

**Comment by GeorgeS2019** [comment]
> Rust is lucky to have [burn](https://github.com/tracel-ai/burn), which is both flexible and also has a good community of developers, but I don't know what options are available in C#.

Torchsharp ( or PyTorch for c#) for c# tries to adopt similar syntax as PyTorch. Most of the time, one just has to copy and paste and make some small adjustments.

Thx for feedback.
