### ISSUE TITLE
[Feature request] sb3-burn as Godot4 GDExtension

### ISSUE THREAD

**Issue by GeorgeS2019** [will-maclean/sb3-burn#46]
Currently there is an active Godot4 RL frameworks using pytorch Stable-baselines3. See the 3D gym compatible examples

Godot4 support **RUST** through **addon**: 

- https://github.com/godot-rust/gdext

The Godot4 RL's need to communicate with **pytorch Sb3** could be substituted with Rust **sb3-burn**.

The Godot4 Rust community is often active to look for Rust frameworks to be integrated into Godot Rust community projects.

I shall contact them to get their feedback on this collaboration.

![msedge_WDM0IoggWG](https://github.com/user-attachments/assets/a782f179-c4fc-4513-8f56-cf855434116d)

**Comment by will-maclean** [comment]
Hi,
Thanks for taking an interest in `sb3-burn`! At this point, there's too many changes being made to the structure of the project to start thinking about integration with other projects. Maybe this could be an idea in a few months when the project is a bit more stable :)
